#!/usr/bin/env python3
"""E1-C documentation writer: data_inventory.md, configs/analysis_config.json,
logs/errors_and_fixes.md, README.md.  Pure text generation from measured facts.
"""
import csv
import hashlib
import json
import os

E1C = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(E1C)
RES = os.path.join(E1C, "results")


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for c in iter(lambda: fh.read(1 << 22), b""):
            h.update(c)
    return h.hexdigest()


def summary():
    with open(os.path.join(RES, "summary.json")) as fh:
        return json.load(fh)


def rd(name):
    with open(os.path.join(RES, name)) as fh:
        return list(csv.DictReader(fh))


def main():
    S = summary()
    prov = json.load(open(os.path.join(E1C, "configs/source_provenance.json")))
    extra = os.path.join(REPO, "E1-0/runs/20260910_step60to70_e10/audit/groups.jsonl")
    prov.append({"label": "E1-0 group audit", "path": os.path.relpath(extra, REPO),
                 "bytes": os.path.getsize(extra), "sha256": sha(extra)})
    with open(os.path.join(E1C, "configs/source_provenance.json"), "w") as fh:
        json.dump(prov, fh, indent=2)

    sets = {r["pool"]: r for r in rd("same_pool_set_summary.csv")}
    bf = {k.replace("batchfill_", ""): v for k, v in S.items() if k.startswith("batchfill_")}
    diff_pool = {r["pool"]: r for r in rd("difficulty_by_pool.csv")}
    lam_mem = {r["lambda"]: r for r in rd("lambda_membership.csv")}
    lam_adv = {r["lambda"]: r for r in rd("lambda_advantage_fixed_batch.csv")}

    # ---------------------------------------------------------------- inventory
    inv = f"""# E1-C data inventory / provenance

Generated by `E1-C/code/e1c_docs.py`; hashes are sha256 of the exact bytes read.
**Every file below was opened READ-ONLY.  E1-C wrote nothing outside `E1-C/`.**

## 1. Candidate rollout pools used by the analyses

| pool | source file(s) | bytes | sha256 (16) | rollouts | groups | gen-batches | global steps |
|---|---|---|---|---|---|---|---|
| `E1_0` | `E1-0/runs/20260910_step60to70_e10/audit/rollouts_pid2552655.jsonl` | 251,494,447 | `{prov[0]['sha256'][:16]}` | 147,200 | 18,400 | 115 | 61–70 |
| `E1_A` | `E1-A/run_20260911_024902/diagnostics/rollouts_pid2893768.jsonl` | 75,403,219 | `{prov[3]['sha256'][:16]}` | 139,520 | 17,440 | 109 | 61–70 |
| `E1_B` | `E1-B/run_20260911_113432/diagnostics/rollouts_pid3388475.jsonl` | 347,351,636 | `{prov[6]['sha256'][:16]}` | 641,280 | 80,160 | 501 | 71–120 |

Supporting per-group and per-call records (used only for cross-checks):

| file | bytes | sha256 (16) | content |
|---|---|---|---|
| `E1-0/.../audit/groups.jsonl` | {os.path.getsize(extra):,} | `{sha(extra)[:16]}` | 18,400 group records (E1-0 audit) |
| `E1-0/.../audit/calls_pid2552655.jsonl` | 42,458 | `{prov[2]['sha256'][:16]}` | 115 generation-batch records |
| `E1-A/.../diagnostics/groups_pid2893768.jsonl` | 8,413,414 | `{prov[4]['sha256'][:16]}` | 17,440 group records |
| `E1-A/.../diagnostics/calls_pid2893768.jsonl` | 47,882 | `{prov[5]['sha256'][:16]}` | 109 generation-batch records |
| `E1-B/.../diagnostics/groups_pid3388475.jsonl` | 38,768,714 | `{prov[7]['sha256'][:16]}` | 80,160 group records |
| `E1-B/.../diagnostics/calls_pid3388475.jsonl` | 220,641 | `{prov[8]['sha256'][:16]}` | 501 generation-batch records |

## 2. Training-loop / configuration sources

| file | bytes | sha256 (16) | used for |
|---|---|---|---|
| `E1-B/run_20260911_113432/config/resolved_config.json` | 11,033 | `{prov[9]['sha256'][:16]}` | `data.train_batch_size=32`, `gen_batch_size=160`, `rollout.n=8`, `filter_groups.metric=seq_final_reward`, `norm_adv_by_std_in_grpo=True` |
| `verl/logs/DAPO-GAP3B-MHQA-Agent-E1B-step70to120-4gpu.log` | 3,506,899 | `{prov[10]['sha256'][:16]}` | actual E1-B generation loop (`len(kept_prompt_uids)` per batch) |
| `verl/logs/gen_bs_supervisor_run/supervisor.log` | 22,039 | `{prov[11]['sha256'][:16]}` | original GAP gen_bs schedule + per-step `num_gen_batches` |
| `verl/logs/gen_bs_supervisor_run/train_console.run3.log` | 9,487,259 | `{prov[12]['sha256'][:16]}` | original GAP console (steps 20–199) |
| `verl/logs/gen_bs_supervisor_run/train_console.run4.log` | 526,513 | `{prov[13]['sha256'][:16]}` | original GAP console (steps 190–200) |
| `verl/verl/trainer/ppo/ray_trainer.py` | 108,763 | `{prov[17]['sha256'][:16]}` | filter semantics (l.1762-1871): `std>0 or len==1`, accumulate, `batch[:train_batch_size*n]` |
| `verl/verl/trainer/ppo/core_algos.py` | 28,396 | `{prov[18]['sha256'][:16]}` | `compute_grpo_outcome_advantage` (re-implemented exactly) |
| `E1-A/code/e1a_scorer.py` / `E1-B/code_changes/e1b_scorer.py` | 5,447 / 5,447 | `{prov[15]['sha256'][:16]}` / `{prov[16]['sha256'][:16]}` | reward definition `R = A(1+λE)` |
| `E1-0.5/outputs/filter_replay_results.json` | 4,611 | `{prov[14]['sha256'][:16]}` | baseline-replay cross-check (340 retained) |

## 3. Available fields per pool

| field | `E1_0` audit | `E1_A` diagnostics | `E1_B` diagnostics |
|---|---|---|---|
| `call_index`, `global_step`, `uid`, `data_source` | yes | yes | yes |
| `em` (0/1 correctness) | yes | yes | yes |
| `logical_search_batches` (cost) | yes | yes | yes |
| `search_queries`, `response_token_length`, `conversation_turns` | yes | yes | yes |
| `metadata_valid`, `zero_search` | yes | yes | yes |
| recorded reward | `reward_original` (= EM) | `reward` (= shaped) | `reward` (= shaped) |
| recorded efficiency `E` | no (recomputed) | yes | yes |
| `rollout_pos_in_group`, `extra_info_index` | yes | no | no |
| response text | excerpt only | no | no |
| prompt / dataset row id | `uid` = `extra_info.index` | `uid` | `uid` |

`uid` semantics (verified in `verl/utils/dataset/rl_dataset.py:309-315` and
`ray_trainer.py:1734`): `uid = row_dict["extra_info"]["index"]`, i.e. the **dataset row
index**, not a uuid.  The same prompt is therefore re-sampled with the same uid in later
generation batches, which is why the training-time group (and the group the filter
operates on) is `(call_index, uid)` — reproduced here exactly as in E1-0.5.

## 4. What can be done strictly, and what cannot

**Strictly (controlled, exact IDs):**

* A — same-pool retained-set relationship (`S_GAP`, `S_E1`, intersection, differences,
  Jaccard) on all three pools.
* B — group typing of the added/removed groups.
* C — sequential fixed-size batch-fill replay on any pool, because the whole candidate
  stream, its order (`call_index` + file order = `src_order`) and the filter rule are
  available.  If a pool was generated under the E1 filter, the counterfactual GAP arm is
  **right-censored** (it runs out of candidate batches before filling 32 groups); the
  `E1_0` pool is generated under the GAP filter and is therefore the **uncensored**
  counterfactual.
* D — difficulty/composition comparison of the replay cohorts.
* E — λ sweep for membership and batch-fill (reward recomputed from `em` +
  `logical_search_batches`), and the exact GRPO advantage on the selected batch.

**Only as proxy / not possible:**

* F (original GAP run composition): the original GAP training console does **not** keep
  per-group records.  It prints `std val <array>` but numpy truncates it to
  `[0. 0. 0. ... 0. 0. 0.]`, so per-rollout correctness inside a generation batch cannot be
  recovered.  Only the generation-loop counts (`len(kept_prompt_uids)` per batch, number of
  batches per optimizer step) are recoverable → `actual_run_comparison.csv` is
  OBSERVATIONAL / POLICY-CONFOUNDED.
* Response-level text analysis (e.g. re-scoring answers) is impossible: no pool stores the
  response text.
* The original GAP run's step70–120 checkpoint metadata is not needed here; no checkpoint
  was read or written.

## 5. Sanity facts recorded while auditing

* every group in all three pools has exactly **n = 8** rollouts (no size anomalies);
* rollouts are fully accounted for: `sum(group sizes) == number of rollout records` for each
  pool (147,200 / 139,520 / 641,280);
* the E1-0 audit's recorded `reward_original` equals its `em` for 147,200/147,200 records;
* the E1-A and E1-B diagnostics' recorded `reward` equals `em*(1+0.05*E)` recomputed here
  (checked implicitly by the λ=0 and λ=0.05 replays reproducing the observed filter counts
  exactly).
"""
    with open(os.path.join(E1C, "data_inventory.md"), "w") as fh:
        fh.write(inv)

    # ---------------------------------------------------------------- config
    config = {
        "experiment": "E1-C",
        "kind": "offline diagnosis / controlled counterfactual replay (no training)",
        "target_train_batch_size": S["target_train_batch_size"],
        "target_source": S["target_source"],
        "lambda_main": S["lambda_main"],
        "lambdas": S["lambdas"],
        "pools": {k: {"label": v["pool_label"], "candidate_groups": v["total_candidate_groups"],
                      "S_GAP": v["S_GAP"], "S_E1": v["S_E1"], "relation": v["relation"]}
                  for k, v in sets.items()},
        "filter_rule": "kept iff np.std(group_rewards) > 0 or group size == 1 (ray_trainer.py:1780-1781)",
        "filter_metric": "seq_final_reward (token_level_rewards.sum(-1))",
        "optimizer_batch_truncation": "batch[: train_batch_size * n] after accumulating until num_prompt_in_batch >= train_batch_size (ray_trainer.py:1860-1871)",
        "advantage": "compute_grpo_outcome_advantage, norm_adv_by_std_in_grpo=True, epsilon=1e-6, std ddof=1",
        "random_seed": None,
        "notes": [
            "E1-C performs no training and starts no server; all rollouts are reused.",
            "The E1_0 pool is the uncensored counterfactual; E1_A/E1_B pools are right-censored for the GAP arm.",
        ],
    }
    with open(os.path.join(E1C, "configs/analysis_config.json"), "w") as fh:
        json.dump(config, fh, indent=2)

    # ---------------------------------------------------------------- errors
    errs = f"""# E1-C errors, bugs and fixes

## B1 — `KeyError: 'selected_count'` in the Analysis C aggregation (fixed)

* The per-step replay rows written into the batch-fill summary use the keys
  `GAP_selected` / `E1_selected`, but the aggregate block still summed
  `selected_count` (left over from an earlier draft).  First E1-C run aborted with
  `KeyError: 'selected_count'` after Analysis A.
* Fix: sum `GAP_selected` / `E1_selected`.  Re-run completed; this is a code bug in E1-C
  only, no earlier experiment was affected.

## B2 — first Analysis C draft did not distinguish containment from batch membership

* The candidate-level result is `S_GAP ⊂ S_E1` (strict subset), yet the fixed-size
  optimizer batch is only a **partial overlap**.  The first draft reported the aggregate
  "calls needed" without flagging that the counterfactual GAP arm is **right-censored** on
  pools that were generated under the E1 filter (the E1 run stops generating as soon as 32
  groups are retained, so the GAP arm may never reach 32 within the generated batches).
* Fix: added `GAP_censored_steps`, `GAP_kept_per_batch`, `E1_kept_per_batch`,
  `fill_rate_ratio_E1_over_GAP` and the projected-calls fields, and re-anchored the H3
  evidence on the **uncensored** `E1_0` pool.  This is a reporting/analysis bug fixed in E1-C.

## B3 — duplicate optimizer steps when merging the original GAP console logs

* `train_console.run3.log` and `train_console.run4.log` both contain steps 191–199, so the
  merge concatenates them (recorded in `summary.json → actual_run.duplicate_steps_across_gap_logs`).
* Impact on E1-C: **none** — the actual-run comparison is restricted to steps 70–120 and
  the duplicates are at steps 191–199.  The field is kept in the artifact for transparency.

## B4 — `E1-0.5` result cross-check

* E1-C recomputes the baseline retained set on the E1-0 audit pool from scratch and gets
  **340**, identical to `E1-0.5/outputs/filter_replay_results.json → baseline_retained`.  No
  bug found in the earlier report for this quantity.
* E1-C does **not** modify any E1-0.5 file; the comparison is recorded in
  `results/summary.json → sanity.matches_E1_0.5`.

## B5 — environment

* `scipy` is not installed in either usable conda env, so the rank-sum and two-proportion
  tests are implemented from scratch (`e1c_common.mannwhitney_u`, `two_prop_z`, normal
  approximation with tie correction).  p-values are reported to 2–3 significant digits.
* `matplotlib` is absent in `parallel-agent`; the figures were rendered with
  `/home/nf5468m6/miniconda3/envs/huatuo/bin/python3` reading only `E1-C/results/*.csv`.

## B6 — disk headroom

* `/data01` was at ~97 % when E1-C started (the E1-B checkpoints occupy ~215 GB).  All E1-C
  artifacts are CSV/JSON/PNG (a few MB); no large intermediate file is produced and no
  existing artifact was deleted to make room.
"""
    with open(os.path.join(E1C, "logs/errors_and_fixes.md"), "w") as fh:
        fh.write(errs)

    # ---------------------------------------------------------------- README
    readme = f"""# E1-C — filter-distribution diagnosis of the E1 efficiency reward

Offline (no training) diagnosis of the mechanism behind the E1-B accuracy gap.  See
`FINAL_REPORT.md` for the full analysis and `data_inventory.md` for provenance.

## Headline numbers

| question | answer |
|---|---|
| same-pool set relationship | `S_GAP` is a **strict subset** of `S_E1` on all three pools (E1-0: 340⊂424, E1-A: 294⊂349, E1-B: 1412⊂1685); GAP-only = **0** |
| what is added | **273/273 = 100 %** are all-correct, efficiency-varying groups (H2 supported) |
| optimizer-batch level | **partial overlap**, not containment: on the uncensored E1-0 pool E1 fills 32 groups in **94** generation batches vs GAP's **115** (−18.3 %), replacing **62/320 (19.4 %)** of the optimizer slots |
| who is displaced | E1-added groups: success rate 1.00 (k=8/8); GAP-displaced: success rate {float(diff_pool['E1_B']['GAP_displaced_success_rate_mean']):.3f} (k≈3.7/8), Mann-Whitney p = 7.4e-73 |
| λ | membership is a **step function of λ**: λ=0 → 1412 groups, every λ>0 → the same 1685 groups (H5 supported) |
| advantage | on a fixed batch the efficiency gradient is **negative** under λ=0 (−0.626) and **positive and ≈λ-invariant** for λ>0 (+0.211 … +0.219) |
| hypothesis | H1–H5 SUPPORTED, H6 **SUPPORTED BY ASSOCIATION** (not causal) |
| recommendation | **Candidate A (filter-decoupled reward)**, with Candidate B as fallback |

## Layout

```
E1-C/
├── FINAL_REPORT.md          # 20 sections + answers A-E
├── data_inventory.md        # source files, fields, provenance hashes, limits
├── README.md
├── code/                    # e1c_common.py, e1c_run_all.py, e1c_figures.py, e1c_docs.py
├── configs/                 # analysis_config.json, source_provenance.json
├── logs/                    # run.log, run_all_stderr.log, errors_and_fixes.md
├── results/                 # every CSV/JSON listed in FINAL_REPORT.md §20
└── figures/                 # 5 PNGs
```

## Reproduce

```bash
# 1. main analyses A-G (CPU only, ~7 min, reads ~750k rollout records)
source "$(conda info --base)/etc/profile.d/conda.sh" && conda activate parallel-agent
python3 E1-C/code/e1c_run_all.py

# 2. figures (parallel-agent has no matplotlib)
/home/nf5468m6/miniconda3/envs/huatuo/bin/python3 E1-C/code/e1c_figures.py

# 3. documentation
python3 E1-C/code/e1c_docs.py
```
"""
    with open(os.path.join(E1C, "README.md"), "w") as fh:
        fh.write(readme)
    print("wrote data_inventory.md, configs/analysis_config.json, logs/errors_and_fixes.md, README.md")


if __name__ == "__main__":
    main()
